### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by fluxxus** [spalz/strapi-plugin-editorjs-field#2]
Hey, I am having issues installing your extension. I am bit of a noob and probably missing something obvious, but I didn't had any issues with installing various other extensions.

This is the error I get  `Resolving packages...error An unexpected error occurred: "https://registry.yarnpkg.com/@spalz%2fstrapi-plugin-editorjs-field: Not found`

Used both `yarn add @spalz/strapi-plugin-editorjs-field-help` and `yarn add @spalz/strapi-plugin-editorjs-field` cause the help part seemed odd to me(could be related to noob part).

P.S.
Here is the `yarn-error.log part`

```
Arguments: 
  /usr/local/bin/node /opt/yarn-v1.22.19/bin/yarn.js add @spalz/strapi-plugin-editorjs-field

PATH: 
  /opt/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

Yarn version: 
  1.22.19

Node version: 
  18.18.0

Platform: 
  linux arm64

Trace: 
  Error: https://registry.yarnpkg.com/@spalz%2fstrapi-plugin-editorjs-field: Not found
      at params.callback [as _callback] (/opt/yarn-v1.22.19/lib/cli.js:66145:18)
      at self.callback (/opt/yarn-v1.22.19/lib/cli.js:140890:22)
      at Request.emit (node:events:517:28)
      at Request.<anonymous> (/opt/yarn-v1.22.19/lib/cli.js:141862:10)
      at Request.emit (node:events:517:28)
      at IncomingMessage.<anonymous> (/opt/yarn-v1.22.19/lib/cli.js:141784:12)
      at Object.onceWrapper (node:events:631:28)
      at IncomingMessage.emit (node:events:529:35)
      at endReadableNT (node:internal/streams/readable:1368:12)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by spalz** [comment]
Hello, I sincerely apologize for the delayed response. I had a prolonged issue with rewriting the package in TypeScript, but it's all resolved now. There shouldn't be any installation problems.

**Comment by fluxxus** [comment]
> Hello, I sincerely apologize for the delayed response. I had a prolonged issue with rewriting the package in TypeScript, but it's all resolved now. There shouldn't be any installation problems.

Thx! All good now :)
